import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import Header from "../_components/Header";
import { SiteHeader } from "@/components/site-header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function layout({ children }) {
  return (
    <div className="[--header-height:calc(theme(spacing.14))] w-full relative">
      <SidebarProvider className="flex flex-col h-screen">
        <SiteHeader />
        <div className="flex flex-1 min-w-0 overflow-hidden">
          <AppSidebar />
          <SidebarInset className="flex-1 min-w-0">
            <main className="p-5 w-full overflow-auto">{children}</main>
          </SidebarInset>
        </div>
      </SidebarProvider>
    </div>
  );
}

export default layout;
