import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Provider from "./_components/auth/Provider";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang="en">
        <body className={poppins.className + "dark antialiased"}>
          <Toaster />
          {children}
        </body>
      </html>
    </Provider>
  );
}
