const users = [
  {
    name: "Jenny Wilson",
    role: "Product Designer",
    department: "Creative",
    email: "jennyw@ahfagon.com",
    phone: "(803) 555-0111",
    status: "Active",
    avatar:
      "https://plus.unsplash.com/premium_photo-1661589836910-b3b0bf644bd5?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cHJvZmVzc2lvbmFsJTIwYmxhY2slMjB3b21hbnxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    name: "Robert Fox",
    role: "Front-End Developer",
    department: "Software",
    email: "robertf@ahfagon.com",
    phone: "(225) 555-0118",
    status: "InActive",
    avatar:
      "https://plus.unsplash.com/premium_photo-1661589836910-b3b0bf644bd5?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cHJvZmVzc2lvbmFsJTIwYmxhY2slMjB3b21hbnxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    name: "Jacob Jones",
    role: "App Developer",
    department: "Software",
    email: "jacobj@ahfagon.com",
    phone: "(270) 555-0117",
    status: "Active",
    avatar:
      "https://plus.unsplash.com/premium_photo-1661589836910-b3b0bf644bd5?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cHJvZmVzc2lvbmFsJTIwYmxhY2slMjB3b21hbnxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    name: "Kristin Watson",
    role: "Back-End Developer",
    department: "Software",
    email: "kristinw@ahfagon.com",
    phone: "(225) 555-0109",
    status: "Active",
    avatar:
      "https://plus.unsplash.com/premium_photo-1661589836910-b3b0bf644bd5?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cHJvZmVzc2lvbmFsJTIwYmxhY2slMjB3b21hbnxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    name: "Cody Fisher",
    role: "Software Engineer",
    department: "Software",
    email: "codyf@ahfagon.com",
    phone: "(480) 555-0103",
    status: "Active",
    avatar:
      "https://plus.unsplash.com/premium_photo-1661589836910-b3b0bf644bd5?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cHJvZmVzc2lvbmFsJTIwYmxhY2slMjB3b21hbnxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    name: "Savannah Nguyen",
    role: "Graphics Engineer",
    department: "Creative",
    email: "nguyens@ahfagon.com",
    phone: "(225) 555-0108",
    status: "Active",
    avatar:
      "https://plus.unsplash.com/premium_photo-1661589836910-b3b0bf644bd5?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cHJvZmVzc2lvbmFsJTIwYmxhY2slMjB3b21hbnxlbnwwfHwwfHx8MA%3D%3D",
  },
];

const tasks = [
  {
    id: "task1",
    title: "Design homepage UI",
    status: "in progress",
    priority: "high",
    assignee: "john.doe@example.com",
    dueDate: "2024-09-10",
  },
  {
    id: "task2",
    title: "Fix login authentication bug",
    status: "pending",
    priority: "medium",
    assignee: "jane.smith@example.com",
    dueDate: "2024-09-15",
  },
  {
    id: "task3",
    title: "Implement payment gateway",
    status: "completed",
    priority: "high",
    assignee: "mike.jones@example.com",
    dueDate: "2024-08-30",
  },
  {
    id: "task4",
    title: "Optimize database queries",
    status: "in progress",
    priority: "low",
    assignee: "susan.white@example.com",
    dueDate: "2024-09-05",
  },
  {
    id: "task5",
    title: "Write API documentation",
    status: "pending",
    priority: "medium",
    assignee: "emma.brown@example.com",
    dueDate: "2024-09-20",
  },
  {
    id: "task3",
    title: "Implement payment gateway",
    status: "completed",
    priority: "high",
    assignee: "mike.jones@example.com",
    dueDate: "2024-08-30",
  },
];

const tableData = [
  {
    date: "Today, 20 Sept 2023",
    total: "22:24:32",
    selectedCount: 2,
    items: [
      {
        id: 1,
        selected: false,
        task: "Branding elements",
        billableStatus: "Billable",
        priority: "High",
        user: "Culhane",
        company: "Zendesk",
        startTime: "12:29",
        endTime: "18:43",
        duration: "3:04:25",
        status: "Completed",
      },
      {
        id: 2,
        selected: false,
        task: "Dashboard Redesign",
        billableStatus: "Non Billable",
        priority: "Low",
        user: "Angel Gouse",
        company: "Toptal",
        startTime: "10:34",
        endTime: "12:50",
        duration: "05:12:09",
        status: "Completed",
      },
      {
        id: 3,
        selected: true,
        task: "Company logos",
        billableStatus: "Billable",
        priority: "High",
        user: "Chance Levin",
        company: "BairesDev",
        startTime: "06:11",
        endTime: "09:32",
        duration: "09:43:00",
        status: "Completed",
      },
      {
        id: 4,
        selected: true,
        task: "IOS Mobile App",
        billableStatus: "Billable",
        priority: "High",
        user: "Kadin Aminoff",
        company: "InVision",
        startTime: "14:22",
        endTime: "16:21",
        duration: "04:33:04",
        status: "Completed",
      },
    ],
  },
  {
    date: "Yesterday, 19 Sept 2023",
    total: "16:26:45",
    items: [
      {
        id: 5,
        selected: false,
        task: "Font End design",
        billableStatus: "Billable",
        priority: "High",
        user: "Talan Calzoni",
        company: "Cuberto",
        startTime: "01:34",
        endTime: "03:12",
        duration: "05:34:43",
        status: "Completed",
      },
      {
        id: 6,
        selected: false,
        task: "Brochure Design",
        billableStatus: "Non Billable",
        priority: "Low",
        user: "Zaire Lipshutz",
        company: "Huge",
        startTime: "15:55",
        endTime: "18:43",
        duration: "04:12:05",
        status: "Completed",
      },
      {
        id: 7,
        selected: false,
        task: "Web Design",
        billableStatus: "Billable",
        priority: "High",
        user: "Lipshutz",
        company: "Frog Design",
        startTime: "07:24",
        endTime: "08:49",
        duration: "02:32:23",
        status: "Completed",
      },
      {
        id: 8,
        selected: false,
        task: "Dashboard Redesign",
        billableStatus: "Non Billable",
        priority: "Low",
        user: "Siphorn",
        company: "UsabilityHub",
        startTime: "01:54",
        endTime: "-",
        duration: "03:32:54",
        status: "Pending",
      },
    ],
  },
];

const projects = [
  {
    owner: "John Doe",
    teamMates: ["Alice Smith", "Bob Johnson", "Charlie Brown"],
    title: "AI Chatbot Development",
    createdAt: "2024-02-20T10:30:00Z",
    status: "completed",
    reason: null,
    description:
      "A chatbot powered by AI to automate customer service responses.",
  },
  {
    owner: "Jane Smith",
    teamMates: ["Tom Hardy", "Emma Watson"],
    title: "E-commerce Platform",
    createdAt: "2024-01-15T08:45:00Z",
    status: "ongoing",
    reason: null,
    description:
      "A full-stack e-commerce platform with secure payment integration.",
  },
  {
    owner: "Michael Johnson",
    teamMates: ["Sarah Lee", "Daniel Green"],
    title: "Health Tracker App",
    createdAt: "2023-12-10T14:20:00Z",
    status: "on hold",
    reason: "Budget constraints",
    description: "A mobile app to monitor daily health and fitness activities.",
  },
  {
    owner: "Emily Davis",
    teamMates: ["Jack Wilson", "Sophia Martinez"],
    title: "Blockchain Voting System",
    createdAt: "2023-11-05T12:00:00Z",
    status: "canceled",
    reason: "Technical limitations",
    description:
      "A decentralized voting system leveraging blockchain technology.",
  },
  {
    owner: "Chris Brown",
    teamMates: ["Olivia Taylor", "Liam White"],
    title: "Smart Home Automation",
    createdAt: "2024-02-05T09:10:00Z",
    status: "ongoing",
    reason: null,
    description:
      "An IoT-based automation system to control home appliances remotely.",
  },
];

export { users, tasks, tableData, projects };
